name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.21.0
      id: review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure with CMake
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CXX_STANDARD=23

      - name: Run clang-tidy
        run: |
          # Example: run on all .cpp files in src/
          find src -name '*.cpp' | xargs clang-tidy -p build

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build with CMake
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_STANDARD=23
          cmake --build build
