name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install LLVM (latest)
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "18.1.0" # Or "18" for bleeding-edge C++23 support

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure with CMake
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CXX_STANDARD=23

      - name: Run clang-tidy
        run: |
          # Example: run on all .cpp files in src/
          find src -name '*.cpp' | xargs clang-tidy -p build

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "18.1.0"

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build with CMake
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_STANDARD=23
          cmake --build build
